import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import {useSession, signIn} from 'next-auth/react'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {data: session} = useSession();
  console.log(session)
  if(session){
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.description}>
            Dangi
          </div>
        </main>
      </>
    )
  }
  else{
    return (
      <>
      <div style={{height:"100vh"}}>
      Not signed in <br />
      <button onClick={()=>{signIn()}}>Sign in</button>
      </div>
        
      </>
    )
  }
}
